---
title: "First Knit"
author: "Monserrat Mendez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attend Palmdale High School, in which I graduated in 2021.Compared to math class, English class involves more reading and writing and less rigorous problem-solving. I am better in my Math classes since English isn't my first language. I have always been better in Art classes due to my creativity and love for colors.


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an HP laptop which I use at home and school. if I'm honest I am not the smartest when it comes to technology, so I choose number 3. I don't have the best internet connection but it's good enough to get work done
   
   
## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name has always been something difficult for some people to say so I'm normally called by one of my last names "Mendez" or "Mora" but if my classmates and instructor are available to say my name I prefer that. My friends normally call me "Monse" or "Mon" since that's the shorter way to say "Monserrat". I don't mind when classmates call me these names but they feel a little too friendly.
   

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to work in the courtroom as a prosecutor, which is the person who institutes legal proceedings against someone. One of UCLA's colleges would help me reach my goals and achieve my dreams. I'm working on getting my political science degree but I also want to get a degree in law and Criminal Justice.
   

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
have gone to Mexico, for vacation meanly to see family. I have never been to the military but would choose the Navy branch since their main job is to protect waterways and provide runaways for the aircraft. 



## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




